server:
  port: 8080

spring:
  application:
    name: greetings-service

greetings-service:
  greeting: "Olá"
  default-value: "QA"

management:
  endpoints:
    web:
      exposure:
        include: '*'